-- CreateEnum
CREATE TYPE "Genre" AS ENUM ('NOVEL', 'POETRY', 'ESSAY', 'HUMANITIES', 'SOCIAL_POLITICS', 'ECONOMICS_BUSINESS', 'SELF_DEVELOPMENT', 'SCIENCE_TECHNOLOGY', 'HISTORY', 'ART_CULTURE', 'TRAVEL', 'CHILDREN_TEEN', 'COMICS');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "preferredGenres" "Genre"[];
