import type { Metadata } from 'next';
import './globals.css';
import { Hahmlet } from 'next/font/google';
import { cn } from '@/lib';

const hahmlet = Hahmlet({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={cn('font-sans', hahmlet.variable)}>
      <body>{children}</body>
    </html>
  );
}
