import { type Book } from '@/lib';

// 외부 도서 검색 API(예: 네이버 도서 검색) 연동 전까지, 검색·추천 흐름을 구현하기 위한 대체 카탈로그.
export const CATALOG: Book[] = [
  {
    id: 'catalog-1',
    title: '해리 포터와 마법사의 돌',
    author: 'J.K. 롤링',
    genre: 'NOVEL',
    publisher: '문학수첩',
  },
  { id: 'catalog-2', title: '1984', author: '조지 오웰', genre: 'NOVEL', publisher: '민음사' },
  { id: 'catalog-2b', title: '1984', author: '조지 오웰', genre: 'NOVEL', publisher: '을유문화사' },
  { id: 'catalog-3', title: '데미안', author: '헤르만 헤세', genre: 'NOVEL', publisher: '민음사' },
  {
    id: 'catalog-4',
    title: '어린 왕자',
    author: '앙투안 드 생텍쥐페리',
    genre: 'NOVEL',
    publisher: '열린책들',
  },
  {
    id: 'catalog-5',
    title: '연금술사',
    author: '파울로 코엘료',
    genre: 'NOVEL',
    publisher: '문학동네',
  },
  { id: 'catalog-6', title: '소년이 온다', author: '한강', genre: 'NOVEL', publisher: '창비' },
  {
    id: 'catalog-7',
    title: '작별하지 않는다',
    author: '한강',
    genre: 'NOVEL',
    publisher: '문학동네',
  },
  {
    id: 'catalog-8',
    title: '나미야 잡화점의 기적',
    author: '히가시노 게이고',
    genre: 'NOVEL',
    publisher: '현대문학',
  },
  {
    id: 'catalog-9',
    title: '살인자의 기억법',
    author: '김영하',
    genre: 'NOVEL',
    publisher: '문학동네',
  },
  { id: 'catalog-10', title: '언어의 온도', author: '이기주', genre: 'ESSAY', publisher: '말글터' },
  {
    id: 'catalog-11',
    title: '멀리 가는 힘',
    author: '이슬아',
    genre: 'ESSAY',
    publisher: '헤엄출판사',
  },
  {
    id: 'catalog-12',
    title: '지구 끝의 온실',
    author: '김초엽',
    genre: 'NOVEL',
    publisher: '자이언트북스',
  },
  {
    id: 'catalog-13',
    title: '팩트풀니스',
    author: '한스 로슬링',
    genre: 'SOCIAL_POLITICS',
    publisher: '김영사',
  },
  {
    id: 'catalog-14',
    title: '넛지',
    author: '리처드 탈러',
    genre: 'ECONOMICS_BUSINESS',
    publisher: '리더스북',
  },
  {
    id: 'catalog-15',
    title: '아웃라이어',
    author: '말콤 글래드웰',
    genre: 'SELF_DEVELOPMENT',
    publisher: '김영사',
  },
  {
    id: 'catalog-16',
    title: '침묵의 봄',
    author: '레이첼 카슨',
    genre: 'SCIENCE_TECHNOLOGY',
    publisher: '에코리브르',
  },
  {
    id: 'catalog-17',
    title: '이기적 유전자',
    author: '리처드 도킨스',
    genre: 'SCIENCE_TECHNOLOGY',
    publisher: '을유문화사',
  },
  {
    id: 'catalog-18',
    title: '조선왕조실록',
    author: '이덕일',
    genre: 'HISTORY',
    publisher: '위즈덤하우스',
  },
  {
    id: 'catalog-19',
    title: '유럽 도시 기행',
    author: '유시민',
    genre: 'TRAVEL',
    publisher: '생각의길',
  },
  {
    id: 'catalog-20',
    title: '슬램덩크',
    author: '이노우에 다케히코',
    genre: 'COMICS',
    publisher: '대현동림',
  },
  { id: 'catalog-21', title: '완득이', author: '김려령', genre: 'NOVEL', publisher: '창비' },
  {
    id: 'catalog-22',
    title: '역행자',
    author: '자청',
    genre: 'SELF_DEVELOPMENT',
    publisher: '웅진지식하우스',
  },
  {
    id: 'catalog-23',
    title: '돈의 심리학',
    author: '모건 하우절',
    genre: 'ECONOMICS_BUSINESS',
    publisher: '인플루엔셀',
  },
  {
    id: 'catalog-24',
    title: '트렌드 코리아 2024',
    author: '김난도',
    genre: 'ECONOMICS_BUSINESS',
    publisher: '미래의창',
  },
  {
    id: 'catalog-25',
    title: '보건교사 안은영',
    author: '정세랑',
    genre: 'NOVEL',
    publisher: '민음사',
  },
  { id: 'catalog-26', title: '파친코', author: '이민진', genre: 'NOVEL', publisher: '문학사상' },
  {
    id: 'catalog-27',
    title: '노르웨이의 숲',
    author: '무라카미 하루키',
    genre: 'NOVEL',
    publisher: '민음사',
  },
  {
    id: 'catalog-28',
    title: '1Q84',
    author: '무라카미 하루키',
    genre: 'NOVEL',
    publisher: '문학동네',
  },
  {
    id: 'catalog-29',
    title: '달러구트 꿈 백화점',
    author: '이미예',
    genre: 'NOVEL',
    publisher: '팩토리나인',
  },
  {
    id: 'catalog-30',
    title: '아버지의 해방일지',
    author: '정지아',
    genre: 'NOVEL',
    publisher: '창비',
  },
  {
    id: 'catalog-31',
    title: '작가의 얼굴',
    author: '김영하',
    genre: 'ESSAY',
    publisher: '현대문학',
  },
  { id: 'catalog-32', title: '아무튼, 여행', author: '김민철', genre: 'ESSAY', publisher: '위고' },
  {
    id: 'catalog-33',
    title: '숨결이 바람 될 때',
    author: '폴 칼라니티',
    genre: 'ESSAY',
    publisher: '흐름출판',
  },
  {
    id: 'catalog-34',
    title: '햄릿',
    author: '윌리엄 셰익스피어',
    genre: 'POETRY',
    publisher: '민음사',
  },
  {
    id: 'catalog-35',
    title: '진달래꽃',
    author: '김소월',
    genre: 'POETRY',
    publisher: '문학과지성사',
  },
  {
    id: 'catalog-36',
    title: '하늘과 바람과 별과 시',
    author: '윤동주',
    genre: 'POETRY',
    publisher: '소와다리',
  },
  {
    id: 'catalog-37',
    title: '정의란 무엇인가',
    author: '마이클 샌델',
    genre: 'HUMANITIES',
    publisher: '와이즈베리',
  },
  {
    id: 'catalog-38',
    title: '죽음의 수용소에서',
    author: '빅터 프랭클',
    genre: 'HUMANITIES',
    publisher: '청아출판사',
  },
  {
    id: 'catalog-39',
    title: '수레바퀴 아래서',
    author: '헤르만 헤세',
    genre: 'NOVEL',
    publisher: '민음사',
  },
  { id: 'catalog-40', title: '이방인', author: '알베르 카뮈', genre: 'NOVEL', publisher: '민음사' },
  { id: 'catalog-41', title: '변신', author: '프란츠 카프카', genre: 'NOVEL', publisher: '민음사' },
  {
    id: 'catalog-42',
    title: '조지아 오키프',
    author: '김선현',
    genre: 'ART_CULTURE',
    publisher: '책읽는수요일',
  },
  {
    id: 'catalog-43',
    title: '방구석 미술관',
    author: '조원재',
    genre: 'ART_CULTURE',
    publisher: '블랙피쉬',
  },
  {
    id: 'catalog-44',
    title: '지대넓얕 시즌1',
    author: '채사장',
    genre: 'HUMANITIES',
    publisher: '한빛비즈',
  },
  {
    id: 'catalog-45',
    title: '모모',
    author: '미하엘 엔데',
    genre: 'CHILDREN_TEEN',
    publisher: '비룡소',
  },
  {
    id: 'catalog-46',
    title: '나의 라임오렌지나무',
    author: '조제 마우로 데 바스콘셀로스',
    genre: 'CHILDREN_TEEN',
    publisher: '동녘',
  },
  {
    id: 'catalog-47',
    title: '유토피아',
    author: '토마스 모어',
    genre: 'SOCIAL_POLITICS',
    publisher: '을유문화사',
  },
  {
    id: 'catalog-48',
    title: '1984 다시 읽기',
    author: '박지향',
    genre: 'SOCIAL_POLITICS',
    publisher: '까치',
  },
  {
    id: 'catalog-49',
    title: '떠나든 머물든',
    author: '나탈리 골드버그',
    genre: 'TRAVEL',
    publisher: '한문화',
  },
  {
    id: 'catalog-50',
    title: '실리콘밸리 스토리',
    author: '박순찬',
    genre: 'SCIENCE_TECHNOLOGY',
    publisher: '한빛미디어',
  },
];
