import { BOOK_COLORS } from '@/lib/constants';
import { Book } from './types';

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: '채식주의자',
    author: '한강',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[0]!,
  },
  {
    id: '2',
    title: '82년생 김지영',
    author: '조남주',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[1]!,
  },
  {
    id: '3',
    title: '불편한 편의점',
    author: '김호연',
    genre: '소설',
    status: 'reading',
    color: BOOK_COLORS[2]!,
  },
  {
    id: '4',
    title: '아몬드',
    author: '손원평',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[3]!,
  },
  {
    id: '5',
    title: '죽고 싶지만 떡볶이는 먹고 싶어',
    author: '백세희',
    genre: '에세이',
    status: 'completed',
    color: BOOK_COLORS[4]!,
  },
  {
    id: '6',
    title: '어떻게 살 것인가',
    author: '유시민',
    genre: '인문',
    status: 'on_hold',
    color: BOOK_COLORS[5]!,
  },
  {
    id: '7',
    title: '사피엔스',
    author: '유발 하라리',
    genre: '역사',
    status: 'completed',
    color: BOOK_COLORS[6]!,
  },
  {
    id: '8',
    title: '총, 균, 쇠',
    author: '재레드 다이아몬드',
    genre: '역사',
    status: 'reading',
    color: BOOK_COLORS[7]!,
  },
  {
    id: '9',
    title: '미움받을 용기',
    author: '기시미 이치로',
    genre: '자기계발',
    status: 'completed',
    color: BOOK_COLORS[8]!,
  },
  {
    id: '10',
    title: '원씽',
    author: '게리 켈러',
    genre: '자기계발',
    status: 'not_started',
    color: BOOK_COLORS[9]!,
  },
  {
    id: '11',
    title: '코스모스',
    author: '칼 세이건',
    genre: '과학·기술',
    status: 'completed',
    color: BOOK_COLORS[10]!,
  },
  {
    id: '12',
    title: '나는 나로 살기로 했다',
    author: '김수현',
    genre: '에세이',
    status: 'reading',
    color: BOOK_COLORS[11]!,
  },
  {
    id: '13',
    title: '채식주의자',
    author: '한강',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[0]!,
  },
  {
    id: '14',
    title: '82년생 김지영',
    author: '조남주',
    genre: '소설',
    status: 'on_hold',
    color: BOOK_COLORS[1]!,
  },
  {
    id: '15',
    title: '불편한 편의점',
    author: '김호연',
    genre: '소설',
    status: 'not_started',
    color: BOOK_COLORS[2]!,
  },
  {
    id: '16',
    title: '아몬드',
    author: '손원평',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[3]!,
  },
  {
    id: '17',
    title: '죽고 싶지만 떡볶이는 먹고 싶어',
    author: '백세희',
    genre: '에세이',
    status: 'completed',
    color: BOOK_COLORS[4]!,
  },
  {
    id: '18',
    title: '어떻게 살 것인가',
    author: '유시민',
    genre: '인문',
    status: 'reading',
    color: BOOK_COLORS[5]!,
  },
  {
    id: '19',
    title: '사피엔스',
    author: '유발 하라리',
    genre: '역사',
    status: 'completed',
    color: BOOK_COLORS[6]!,
  },
  {
    id: '20',
    title: '총, 균, 쇠',
    author: '재레드 다이아몬드',
    genre: '역사',
    status: 'reading',
    color: BOOK_COLORS[7]!,
  },
  {
    id: '21',
    title: '미움받을 용기',
    author: '기시미 이치로',
    genre: '자기계발',
    status: 'completed',
    color: BOOK_COLORS[8]!,
  },
  {
    id: '22',
    title: '원씽',
    author: '게리 켈러',
    genre: '자기계발',
    status: 'reading',
    color: BOOK_COLORS[9]!,
  },
  {
    id: '23',
    title: '코스모스',
    author: '칼 세이건',
    genre: '과학·기술',
    status: 'completed',
    color: BOOK_COLORS[10]!,
  },
  {
    id: '24',
    title: '나는 나로 살기로 했다',
    author: '김수현',
    genre: '에세이',
    status: 'reading',
    color: BOOK_COLORS[11]!,
  },
  {
    id: '25',
    title: '채식주의자',
    author: '한강',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[0]!,
  },
  {
    id: '26',
    title: '82년생 김지영',
    author: '조남주',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[1]!,
  },
  {
    id: '27',
    title: '불편한 편의점',
    author: '김호연',
    genre: '소설',
    status: 'reading',
    color: BOOK_COLORS[2]!,
  },
  {
    id: '28',
    title: '아몬드',
    author: '손원평',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[3]!,
  },
  {
    id: '29',
    title: '죽고 싶지만 떡볶이는 먹고 싶어',
    author: '백세희',
    genre: '에세이',
    status: 'completed',
    color: BOOK_COLORS[4]!,
  },
  {
    id: '30',
    title: '어떻게 살 것인가',
    author: '유시민',
    genre: '인문',
    status: 'reading',
    color: BOOK_COLORS[5]!,
  },
  {
    id: '31',
    title: '사피엔스',
    author: '유발 하라리',
    genre: '역사',
    status: 'completed',
    color: BOOK_COLORS[6]!,
  },
  {
    id: '32',
    title: '총, 균, 쇠',
    author: '재레드 다이아몬드',
    genre: '역사',
    status: 'reading',
    color: BOOK_COLORS[7]!,
  },
  {
    id: '33',
    title: '미움받을 용기',
    author: '기시미 이치로',
    genre: '자기계발',
    status: 'completed',
    color: BOOK_COLORS[8]!,
  },
  {
    id: '34',
    title: '원씽',
    author: '게리 켈러',
    genre: '자기계발',
    status: 'reading',
    color: BOOK_COLORS[9]!,
  },
  {
    id: '35',
    title: '코스모스',
    author: '칼 세이건',
    genre: '과학·기술',
    status: 'completed',
    color: BOOK_COLORS[10]!,
  },
  {
    id: '36',
    title: '나는 나로 살기로 했다',
    author: '김수현',
    genre: '에세이',
    status: 'reading',
    color: BOOK_COLORS[11]!,
  },
  {
    id: '37',
    title: '채식주의자',
    author: '한강',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[0]!,
  },
  {
    id: '38',
    title: '82년생 김지영',
    author: '조남주',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[1]!,
  },
  {
    id: '39',
    title: '불편한 편의점',
    author: '김호연',
    genre: '소설',
    status: 'reading',
    color: BOOK_COLORS[2]!,
  },
  {
    id: '40',
    title: '아몬드',
    author: '손원평',
    genre: '소설',
    status: 'completed',
    color: BOOK_COLORS[3]!,
  },
  {
    id: '41',
    title: '죽고 싶지만 떡볶이는 먹고 싶어',
    author: '백세희',
    genre: '에세이',
    status: 'completed',
    color: BOOK_COLORS[4]!,
  },
  {
    id: '42',
    title: '어떻게 살 것인가',
    author: '유시민',
    genre: '인문',
    status: 'reading',
    color: BOOK_COLORS[5]!,
  },
  {
    id: '43',
    title: '사피엔스',
    author: '유발 하라리',
    genre: '역사',
    status: 'completed',
    color: BOOK_COLORS[6]!,
  },
  {
    id: '44',
    title: '총, 균, 쇠',
    author: '재레드 다이아몬드',
    genre: '역사',
    status: 'reading',
    color: BOOK_COLORS[7]!,
  },
  {
    id: '45',
    title: '미움받을 용기',
    author: '기시미 이치로',
    genre: '자기계발',
    status: 'completed',
    color: BOOK_COLORS[8]!,
  },
  {
    id: '46',
    title: '원씽',
    author: '게리 켈러',
    genre: '자기계발',
    status: 'reading',
    color: BOOK_COLORS[9]!,
  },
  {
    id: '47',
    title: '코스모스',
    author: '칼 세이건',
    genre: '과학·기술',
    status: 'completed',
    color: BOOK_COLORS[10]!,
  },
  {
    id: '48',
    title: '나는 나로 살기로 했다',
    author: '김수현',
    genre: '에세이',
    status: 'reading',
    color: BOOK_COLORS[11]!,
  },
];
