import { BOOK_COLORS } from '@/lib/constants/book';
import { type Book, type ReadingNote } from '@/lib';

export const MOCK_BOOKS: Book[] = [
  { id: '1', title: '채식주의자', author: '한강', genre: 'NOVEL' },
  { id: '2', title: '82년생 김지영', author: '조남주', genre: 'NOVEL' },
  { id: '3', title: '불편한 편의점', author: '김호연', genre: 'NOVEL' },
  { id: '4', title: '아몬드', author: '손원평', genre: 'NOVEL' },
  { id: '5', title: '죽고 싶지만 떡볶이는 먹고 싶어', author: '백세희', genre: 'ESSAY' },
  { id: '6', title: '어떻게 살 것인가', author: '유시민', genre: 'HUMANITIES' },
  { id: '7', title: '사피엔스', author: '유발 하라리', genre: 'HISTORY' },
  { id: '8', title: '총, 균, 쇠', author: '재레드 다이아몬드', genre: 'HISTORY' },
  { id: '9', title: '미움받을 용기', author: '기시미 이치로', genre: 'SELF_DEVELOPMENT' },
  { id: '10', title: '원씽', author: '게리 켈러', genre: 'SELF_DEVELOPMENT' },
  { id: '11', title: '코스모스', author: '칼 세이건', genre: 'SCIENCE_TECHNOLOGY' },
  { id: '12', title: '나는 나로 살기로 했다', author: '김수현', genre: 'ESSAY' },
  { id: '13', title: '채식주의자', author: '한강', genre: 'NOVEL' },
  { id: '14', title: '82년생 김지영', author: '조남주', genre: 'NOVEL' },
  { id: '15', title: '불편한 편의점', author: '김호연', genre: 'NOVEL' },
  { id: '16', title: '아몬드', author: '손원평', genre: 'NOVEL' },
  { id: '17', title: '죽고 싶지만 떡볶이는 먹고 싶어', author: '백세희', genre: 'ESSAY' },
  { id: '18', title: '어떻게 살 것인가', author: '유시민', genre: 'HUMANITIES' },
  { id: '19', title: '사피엔스', author: '유발 하라리', genre: 'HISTORY' },
  { id: '20', title: '총, 균, 쇠', author: '재레드 다이아몬드', genre: 'HISTORY' },
  { id: '21', title: '미움받을 용기', author: '기시미 이치로', genre: 'SELF_DEVELOPMENT' },
  { id: '22', title: '원씽', author: '게리 켈러', genre: 'SELF_DEVELOPMENT' },
  { id: '23', title: '코스모스', author: '칼 세이건', genre: 'SCIENCE_TECHNOLOGY' },
  { id: '24', title: '나는 나로 살기로 했다', author: '김수현', genre: 'ESSAY' },
  { id: '25', title: '채식주의자', author: '한강', genre: 'NOVEL' },
  { id: '26', title: '82년생 김지영', author: '조남주', genre: 'NOVEL' },
  { id: '27', title: '불편한 편의점', author: '김호연', genre: 'NOVEL' },
  { id: '28', title: '아몬드', author: '손원평', genre: 'NOVEL' },
  { id: '29', title: '죽고 싶지만 떡볶이는 먹고 싶어', author: '백세희', genre: 'ESSAY' },
  { id: '30', title: '어떻게 살 것인가', author: '유시민', genre: 'HUMANITIES' },
  { id: '31', title: '사피엔스', author: '유발 하라리', genre: 'HISTORY' },
  { id: '32', title: '총, 균, 쇠', author: '재레드 다이아몬드', genre: 'HISTORY' },
  { id: '33', title: '미움받을 용기', author: '기시미 이치로', genre: 'SELF_DEVELOPMENT' },
  { id: '34', title: '원씽', author: '게리 켈러', genre: 'SELF_DEVELOPMENT' },
  { id: '35', title: '코스모스', author: '칼 세이건', genre: 'SCIENCE_TECHNOLOGY' },
  { id: '36', title: '나는 나로 살기로 했다', author: '김수현', genre: 'ESSAY' },
  { id: '37', title: '채식주의자', author: '한강', genre: 'NOVEL' },
  { id: '38', title: '82년생 김지영', author: '조남주', genre: 'NOVEL' },
  { id: '39', title: '불편한 편의점', author: '김호연', genre: 'NOVEL' },
  { id: '40', title: '아몬드', author: '손원평', genre: 'NOVEL' },
  { id: '41', title: '죽고 싶지만 떡볶이는 먹고 싶어', author: '백세희', genre: 'ESSAY' },
  { id: '42', title: '어떻게 살 것인가', author: '유시민', genre: 'HUMANITIES' },
  { id: '43', title: '사피엔스', author: '유발 하라리', genre: 'HISTORY' },
  { id: '44', title: '총, 균, 쇠', author: '재레드 다이아몬드', genre: 'HISTORY' },
  { id: '45', title: '미움받을 용기', author: '기시미 이치로', genre: 'SELF_DEVELOPMENT' },
  { id: '46', title: '원씽', author: '게리 켈러', genre: 'SELF_DEVELOPMENT' },
  { id: '47', title: '코스모스', author: '칼 세이건', genre: 'SCIENCE_TECHNOLOGY' },
  { id: '48', title: '나는 나로 살기로 했다', author: '김수현', genre: 'ESSAY' },
];

export const MOCK_READING_NOTES: Record<string, ReadingNote> = {
  '1': { status: 'COMPLETED', color: BOOK_COLORS[0]! },
  '2': { status: 'COMPLETED', color: BOOK_COLORS[1]! },
  '3': { status: 'READING', color: BOOK_COLORS[2]! },
  '4': { status: 'COMPLETED', color: BOOK_COLORS[3]! },
  '5': { status: 'COMPLETED', color: BOOK_COLORS[4]! },
  '6': { status: 'ON_HOLD', color: BOOK_COLORS[5]! },
  '7': { status: 'COMPLETED', color: BOOK_COLORS[6]! },
  '8': { status: 'READING', color: BOOK_COLORS[7]! },
  '9': { status: 'COMPLETED', color: BOOK_COLORS[8]! },
  '10': { status: 'NOT_STARTED', color: BOOK_COLORS[9]! },
  '11': { status: 'COMPLETED', color: BOOK_COLORS[10]! },
  '12': { status: 'READING', color: BOOK_COLORS[11]! },
  '13': { status: 'COMPLETED', color: BOOK_COLORS[0]! },
  '14': { status: 'ON_HOLD', color: BOOK_COLORS[1]! },
  '15': { status: 'NOT_STARTED', color: BOOK_COLORS[2]! },
  '16': { status: 'COMPLETED', color: BOOK_COLORS[3]! },
  '17': { status: 'COMPLETED', color: BOOK_COLORS[4]! },
  '18': { status: 'READING', color: BOOK_COLORS[5]! },
  '19': { status: 'COMPLETED', color: BOOK_COLORS[6]! },
  '20': { status: 'READING', color: BOOK_COLORS[7]! },
  '21': { status: 'COMPLETED', color: BOOK_COLORS[8]! },
  '22': { status: 'READING', color: BOOK_COLORS[9]! },
  '23': { status: 'COMPLETED', color: BOOK_COLORS[10]! },
  '24': { status: 'READING', color: BOOK_COLORS[11]! },
  '25': { status: 'COMPLETED', color: BOOK_COLORS[0]! },
  '26': { status: 'COMPLETED', color: BOOK_COLORS[1]! },
  '27': { status: 'READING', color: BOOK_COLORS[2]! },
  '28': { status: 'COMPLETED', color: BOOK_COLORS[3]! },
  '29': { status: 'COMPLETED', color: BOOK_COLORS[4]! },
  '30': { status: 'READING', color: BOOK_COLORS[5]! },
  '31': { status: 'COMPLETED', color: BOOK_COLORS[6]! },
  '32': { status: 'READING', color: BOOK_COLORS[7]! },
  '33': { status: 'COMPLETED', color: BOOK_COLORS[8]! },
  '34': { status: 'READING', color: BOOK_COLORS[9]! },
  '35': { status: 'COMPLETED', color: BOOK_COLORS[10]! },
  '36': { status: 'READING', color: BOOK_COLORS[11]! },
  '37': { status: 'COMPLETED', color: BOOK_COLORS[0]! },
  '38': { status: 'COMPLETED', color: BOOK_COLORS[1]! },
  '39': { status: 'READING', color: BOOK_COLORS[2]! },
  '40': { status: 'COMPLETED', color: BOOK_COLORS[3]! },
  '41': { status: 'COMPLETED', color: BOOK_COLORS[4]! },
  '42': { status: 'READING', color: BOOK_COLORS[5]! },
  '43': { status: 'COMPLETED', color: BOOK_COLORS[6]! },
  '44': { status: 'READING', color: BOOK_COLORS[7]! },
  '45': { status: 'COMPLETED', color: BOOK_COLORS[8]! },
  '46': { status: 'READING', color: BOOK_COLORS[9]! },
  '47': { status: 'COMPLETED', color: BOOK_COLORS[10]! },
  '48': { status: 'READING', color: BOOK_COLORS[11]! },
};
